// <auto-generated />
namespace SistemaPasteleria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Agregandollavesforaneas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agregandollavesforaneas));
        
        string IMigrationMetadata.Id
        {
            get { return "202103011841400_Agregando-llaves-foraneas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
